### PR TITLE
feat(rss): get date from rss item

### PR DESCRIPTION
**Pull request by thomascarvalho**
Hi, nice work with this plugin.

This PR contains changes to retrieve the publication date of RSS items

### CODE REVIEW

**Comment by secretfader** [comment]
Thanks for the great PR! I'll get this merged and released later today.

**Comment by secretfader** [comment]
Release `0.3.0`, which includes changes from this PR, is out now.

I also noticed you enhanced the test suite. I had forgot about the `.toBeCalledWith` API in Jest, so thanks for making use of that! :+1:

**Comment by thomascarvalho** [comment]
Cool 👍 Thanks for the release, I'm going to use it on my project.

**Comment by secretfader** [comment]
Cool. Let me know if you see anything else that needs a change, @thomascarvalho. I love getting PRs that are solid and easy to merge.

**Pull request merged**
