### PR TITLE
feat(parse): convert node date field to date

### PR DESCRIPTION
**Pull request by thomascarvalho**
This PR convert rss node date field to Date type.
This should solve #2

### CODE REVIEW

**Comment by secretfader** [comment]
Thanks, @thomascarvalho! I just assigned you a commit bit on this repo. 

I'll merge this PR and cut a new release promptly.

**Comment by secretfader** [comment]
Didn't mean to close the PR. Whoops.

**Comment by thomascarvalho** [comment]
Thanks @secretfader, I will try to help if there are other issues

**Comment by secretfader** [comment]
I really appreciate it, @thomascarvalho! :+1:

**Pull request merged**
